name: Omega Python Package (Conda)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.10, 3.11]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Conda
        uses: actions/cache@v3
        with:
          path: ~/.conda
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-

      - name: Install mamba
        run: conda install mamba -c conda-forge

      - name: Create environment
        run: mamba env create --file environment.yml --name omega

      - name: Activate environment and install test tools
        run: |
          source activate omega
          mamba install flake8 pytest

      - name: Lint with flake8
        run: |
          source activate omega
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          source activate omega
          pytest

      # Optional: upload documentation or outputs
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: docs
      #     path: docs/_build/html/
